workers:
  - name: telegram-trading-bot
    plan: free
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false